### ISSUE TITLE
Bdy-1px not working

### ISSUE THREAD

**Issue by ankuram** [yahoo/atomizer#152]
@renatoi 

The class BDy-1px doesn't appear to be working.
It does show up in the config, but the css file doesn't have that class.

**Comment by thierryk** [comment]
@ankuram is that `BDy-1px` or is that a typo (meant to be `Bdy-1px`)?
Also, do you have other classes related to border on the same node?
Because styling something with `border-width` alone would not create a border (you'd need `border-style` too).

Note that we also have [**helper** classes for borders](https://git.corp.yahoo.com/yahoodotcom/yahoocss/wiki/Transitioning-from-Stencil-to-Atomic-CSS#borders).

**Comment by renatoi** [comment]
As @thierryk said, Bdy-1px is not supported. If you want border 1px, you can use the Bd helper which adds border-width of 1px and border-style of 1px.
