### ISSUE TITLE
What happened to the "Arrow" classes?

### ISSUE THREAD

**Issue by xvash** [yahoo/atomizer#167]
We still use the .Arrow.North... classes for the tooltip arrow. I don't see them anywhere in the yahoocss and I wouldn't want to replace them with atomic equivalent classes.

I suppose I could just add them to our own custom css in the mean time.

**Comment by thierryk** [comment]
Are you only using `.Arrow.North`? Because if you do then the styles in both of those rules could be grouped and you could submit a PR to include what you need into this file: https://git.corp.yahoo.com/yahoodotcom/yahoocss/blob/master/css/patch.css

This way, if it is relevant, we can easily share this across the board, by including it into `custom.css` for example (in yahoocss).

**Comment by thierryk** [comment]
Please open an issue on corp.
