### ISSUE TITLE
IE fallbacks

### ISSUE THREAD

**Issue by xvash** [yahoo/atomizer#186]
One fallback we noticed is missing is the IE filter opacity as an opacity fallback for IE8/7

How about font rem fallbacks etc?

**Comment by thierryk** [comment]
@xvash @renatoi is going to include a patch to support opacity in oldIE, but we have no plan to support a `rem` fallback in Atomizer because this styling depends on `:root` (`<html>`) and Atomizer does not know anything about the styling of other elements &mdash; like things coming from a base style sheets. 

Is your concern about `rem` related to my.yahoo? Because only my.yahoo should use `rem`. @renatoi noticed that the homepage is using Stencil legacy though, which is plain **wrong** as we have a "desktop" version for any other property than my.yahoo.com
