### ISSUE TITLE
Create gitter room/badge for readme

### ISSUE THREAD

**Issue by corysimmons** [yahoo/atomizer#201]
It might be helpful for people new to the technology to be able to chat with each other (and the maintainer) instead of opening up 50 issues. :)

**Comment by corysimmons** [comment]
Example question:

Take the following HTML

```html
<nav>
  <a href="#" class="C(#ff0) P(20px)">Link</a>
  <a href="#" class="C(#ff0) P(20px)">Link</a>
  <a href="#" class="C(#ff0) P(20px)">Link</a>
</nav>
```

What if I suddenly want to change the color of all the links? Is there a convenient way to do this or should I just use a standard class for setting the same type of elements styles?

**Comment by renatoi** [comment]
Hey cory,

Yes, I guess it's a good idea to create a Gitter :)

As for the example question (not sure if you want it answered here or if it's just an example), we usually tell people that you have to be pragmatic, think what's the best solution for you that will fit your case. Here's some options:

   1. Use a template engine or a component library. When you use components it's easier to manage styles and propagate design changes. For instance, you could have a `<Nav>` component in React, Angular, Ember, etc, that iterates through the links. So you write it only once in your code and it becomes your source of truth. However, there are times that you might want this same design to also be on other components. Be aware though, that creating "global" styles may lead to some architectural problems when your app scales, since you are coupling styles in different components. But let's be pragmatic, some styles need to affect more than one component. In this case you have other options.

   2. Use atomic css variables. Did you know you can have them?

```html
<nav>
  <a href="#" class="C($link-color) P($gutter-xl)">Link</a>
  <a href="#" class="C($link-color) P($gutter-xl)">Link</a>
  <a href="#" class="C($link-color) P($gutter-xl)">Link</a>
</nav>
```

If you need to change the $link-color, you just set the new value in the [config file](https://github.com/yahoo/atomizer/blob/master/examples/example-config.js):

```js
{
  custom: {
    'C($link-color)': '#ff0',
    'P($gutter-xl)': '20px'
  }
}
```

   3. Be pragmatic: If you think this is too much to handle at the atomic level, pick the right tool for you. In this case, go classic semantic CSS. We suggest you use "BEM" naming convetion (I personally prefer the [SUITCSS](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) variation of it). In most cases, Atomic should handle these cases for you.

**Comment by corysimmons** [comment]
Awesome, thanks for the reply. Really excited about this. Kudos on your presentation on YouTube as well.

**Comment by renatoi** [comment]
Added in PR #205
