### ISSUE TITLE
Parse() and getConfig() don't recognize helper classes 

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#64]
The AutoAtom feature's methods `parse()` and `getConfig()` are not matching helper classes such as `Bfc`

fyi @renatoi @thierryk

**Comment by src-code** [comment]
Need to make sure we have tests that include these classes going forward too

**Comment by thierryk** [comment]
@src-code I'm not sure we should bother with helper classes. In my opinion, `helpers.css` should be treated the same as `base.css`. Also because we are not sure what would make sense to include and what the proper syntax should be. Like a base style sheet, some people may have their own helper sheet already.

I'm more concerned by the oldIE fallback for `display: inline-block` and the `ib-box` (for inline-block box) class we want to offer to replace `D-ib Va-t` and provide the oldIE patch as well. How should we do this? Unlike the helpers style sheet, I believe those should be part of `atomic.css`. May be "baked in", with any atomizer output?

**Comment by src-code** [comment]
I think this one is outdated, as we've talked about bringing back helpers but in their own ruleset?  But for now, `Bfc` and such have been removed from the Atomic ruleset.

Issue #80 covers the oldIE issue you raised here.
